# Makefile for gps process

CC = gcc
CFLAGS = -Wall -I.
LIBS = -lcjson -lpthread -lpaho-mqtt3c

SRCS = main.c mqtt.c pubEmecyThread.c
OBJS = $(SRCS:.c=.o)
TARGET = gpsPub

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) -o $@ $^ $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)
